package gestion;

public enum CodeErreur {
  PSEUDO_DEJA_EXISTANT, PSEUDO_TROP_LONG, NOM_CARACTERE_INVALIDE, MEMBRE_INTROUVABLE, EVENEMENT_INTROUVABLE, ID_NEGATIF, DATE_PASSEE, DATE_NULL, NB_MAX_PERSONNES_TROP_PETIT, TYPE_NULL, NOM_NULL, NOM_ESPACE_EN_TROP, NOM_VIDE, NOM_TROP_LONG, DESCRIPTIF_NULL, DESCRIPTIF_VIDE, DESCRIPTIF_ESPACE_EN_TROP, DESCRIPTIF_TROP_LONG, LIEU_NULL, LIEU_ESPACE_EN_TROP, LIEU_VIDE, LIEU_TROP_LONG
}
